# Generated by Django 5.2.12 on 2026-05-09 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FidsDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pantalla', models.CharField(max_length=20, unique=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('estado_conexion', models.CharField(choices=[('ONLINE', 'En línea'), ('OFFLINE', 'Fuera de línea')], default='OFFLINE', max_length=20)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo FIDS',
                'db_table': 'fids_dispositivos',
            },
        ),
        migrations.CreateModel(
            name='FidsPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plantilla', models.CharField(max_length=50)),
                ('esquema_colores', models.CharField(max_length=100)),
                ('fuente_texto', models.CharField(max_length=50)),
                ('idiomas_visualizacion', models.CharField(max_length=50)),
                ('columnas_visibles', models.JSONField()),
            ],
            options={
                'verbose_name': 'Plantilla FIDS',
                'db_table': 'fids_plantillas',
            },
        ),
        migrations.CreateModel(
            name='FidsZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=50)),
                ('tipo_filtro_vuelo', models.CharField(choices=[('LLEGADAS_SOLO', 'Llegadas Solo'), ('SALIDAS_SOLO', 'Salidas Solo'), ('MIXTO', 'Mixto (Llegadas y Salidas)')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Zona FIDS',
                'verbose_name_plural': 'Zonas FIDS',
                'db_table': 'fids_zonas',
            },
        ),
        migrations.CreateModel(
            name='FidsAlertaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_alerta', models.TextField()),
                ('tipo_gravedad', models.CharField(choices=[('URGENTE', 'Urgente'), ('INFORMATIVO', 'Informativo')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('expira_at', models.DateTimeField()),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pantalla_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='pantallas_fids.fidsdispositivo')),
            ],
            options={
                'verbose_name': 'Alerta FIDS',
                'db_table': 'fids_alertas_emergencia',
            },
        ),
        migrations.AddField(
            model_name='fidsdispositivo',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pantallas_fids.fidsplantilla'),
        ),
        migrations.AddField(
            model_name='fidsdispositivo',
            name='zona_fids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='pantallas_fids.fidszona'),
        ),
    ]
