# Generated by Django 5.2.12 on 2026-05-08 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad_iam', '0001_initial'),
        ('vuelos_aodb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPuerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_puerta', models.CharField(max_length=10, unique=True)),
                ('envergadura_maxima_aceptada', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('vuelo_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puertas_asignadas', to='vuelos_aodb.vuelodiario')),
            ],
            options={
                'verbose_name': 'Asignación de Puerta',
                'db_table': 'asignacion_puertas',
            },
        ),
        migrations.CreateModel(
            name='CintaEquipaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cinta', models.CharField(max_length=10, unique=True)),
                ('ubicacion_zona', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'Mantenimiento')], default='ACTIVO', max_length=20)),
                ('vuelo_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuelos_aodb.vuelodiario')),
            ],
            options={
                'verbose_name': 'Cinta de Equipaje',
                'db_table': 'cintas_equipaje',
            },
        ),
        migrations.CreateModel(
            name='MostradorCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mostrador', models.CharField(max_length=10, unique=True)),
                ('hora_apertura', models.DateTimeField(blank=True, null=True)),
                ('hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='CERRADO', max_length=20)),
                ('aerolinea_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad_iam.aerolineaempresa')),
                ('vuelo_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuelos_aodb.vuelodiario')),
            ],
            options={
                'verbose_name': 'Mostrador de Check-in',
                'db_table': 'mostradores_checkin',
            },
        ),
        migrations.CreateModel(
            name='PosicionRampa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_posicion', models.CharField(max_length=10, unique=True)),
                ('coordenadas_mapa', models.JSONField(blank=True, help_text='JSON de geolocalización o coordenadas de dibujo', null=True)),
                ('estado', models.CharField(choices=[('OCUPADO', 'Ocupado'), ('LIBRE', 'Libre'), ('RESERVADO', 'Reservado')], default='LIBRE', max_length=20)),
                ('vuelo_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuelos_aodb.vuelodiario')),
            ],
            options={
                'verbose_name': 'Posición de Rampa',
                'db_table': 'posiciones_rampa',
            },
        ),
    ]
