# Generated by Django 5.2.12 on 2026-05-05 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiccAerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(max_length=100)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('codigo_icao', models.CharField(max_length=4, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Diccionario Aerolínea',
                'verbose_name_plural': 'Diccionario Aerolíneas',
                'db_table': 'dicc_aerolineas',
            },
        ),
        migrations.CreateModel(
            name='DiccAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad_max_pasajeros', models.IntegerField()),
                ('envergadura_categoria', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Diccionario Aeronave',
                'verbose_name_plural': 'Diccionario Aeronaves',
                'db_table': 'dicc_aeronaves',
            },
        ),
        migrations.CreateModel(
            name='DiccAeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('codigo_icao', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'Diccionario Aeropuerto',
                'verbose_name_plural': 'Diccionario Aeropuertos',
                'db_table': 'dicc_aeropuertos',
            },
        ),
        migrations.CreateModel(
            name='IntegracionWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_nombre', models.CharField(max_length=100)),
                ('webhook_url', models.URLField(max_length=255)),
                ('evento_disparador', models.CharField(max_length=50)),
                ('token_autorizacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Integración Webhook',
                'verbose_name_plural': 'Integraciones Webhooks',
                'db_table': 'integraciones_webhooks',
            },
        ),
        migrations.CreateModel(
            name='MultimonedaTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
                ('simbolo', models.CharField(max_length=5)),
                ('tipo_cambio_ref_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tasa_seguridad_nacional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_seguridad_internacional', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Multi-moneda y Tasa',
                'verbose_name_plural': 'Multi-moneda y Tasas',
                'db_table': 'multimoneda_tasas',
            },
        ),
        migrations.CreateModel(
            name='AeropuertoLocalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aeropuerto', models.CharField(max_length=150)),
                ('telefono_soporte', models.CharField(max_length=20)),
                ('zona_horaria', models.CharField(default='America/La_Paz', max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('aeropuerto_maestro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settings_local', to='configuracion_global.diccaeropuerto')),
            ],
            options={
                'verbose_name': 'Configuración Aeropuerto Local',
                'verbose_name_plural': 'Configuraciones Aeropuerto Local',
                'db_table': 'aeropuerto_local_settings',
            },
        ),
    ]
