# Generated by Django 5.2.12 on 2026-05-08 02:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_global', '0001_initial'),
        ('seguridad_iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VueloDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_vuelo', models.CharField(max_length=10)),
                ('tipo_operacion', models.CharField(choices=[('LLEGADA', 'Llegada'), ('SALIDA', 'Salida')], max_length=10)),
                ('estado', models.CharField(choices=[('A_TIEMPO', 'A Tiempo'), ('DEMORADO', 'Demorado'), ('CANCELADO', 'Cancelado'), ('LANDED', 'Aterrizado'), ('BOARDING', 'Embarcando'), ('DEPARTED', 'Despegado')], default='A_TIEMPO', max_length=20)),
                ('fecha_operacion', models.DateField()),
                ('std', models.DateTimeField(verbose_name='Scheduled Time Departure')),
                ('etd', models.DateTimeField(blank=True, null=True, verbose_name='Estimated Time Departure')),
                ('atd', models.DateTimeField(blank=True, null=True, verbose_name='Actual Time Departure')),
                ('sta', models.DateTimeField(verbose_name='Scheduled Time Arrival')),
                ('eta', models.DateTimeField(blank=True, null=True, verbose_name='Estimated Time Arrival')),
                ('ata', models.DateTimeField(blank=True, null=True, verbose_name='Actual Time Arrival')),
                ('aerolinea_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad_iam.aerolineaempresa')),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion_global.diccaeronave')),
                ('aeropuerto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_destino_diarios', to='configuracion_global.diccaeropuerto')),
                ('aeropuerto_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_origen_diarios', to='configuracion_global.diccaeropuerto')),
            ],
            options={
                'verbose_name': 'Operación del Día',
                'db_table': 'vuelos_diarios',
            },
        ),
        migrations.CreateModel(
            name='ManifiestoPasajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pax', models.IntegerField(default=0)),
                ('pax_ejecutivo', models.IntegerField(default=0)),
                ('pax_turista', models.IntegerField(default=0)),
                ('pax_conexion', models.IntegerField(default=0)),
                ('pax_silla_ruedas', models.IntegerField(default=0)),
                ('infantes_menores', models.IntegerField(default=0)),
                ('peso_equipaje_total_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('peso_carga_total_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vuelo_diario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifiesto', to='vuelos_aodb.vuelodiario')),
            ],
            options={
                'db_table': 'manifiesto_pasajeros',
            },
        ),
        migrations.CreateModel(
            name='HitoRampa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catering_inicio', models.DateTimeField(blank=True, null=True)),
                ('catering_fin', models.DateTimeField(blank=True, null=True)),
                ('combustible_inicio', models.DateTimeField(blank=True, null=True)),
                ('combustible_fin', models.DateTimeField(blank=True, null=True)),
                ('maletas_inicio', models.DateTimeField(blank=True, null=True)),
                ('maletas_fin', models.DateTimeField(blank=True, null=True)),
                ('pushback_realizado', models.DateTimeField(blank=True, null=True)),
                ('operador_rampa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vuelo_diario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='vuelos_aodb.vuelodiario')),
            ],
            options={
                'db_table': 'hitos_rampa',
            },
        ),
        migrations.CreateModel(
            name='VueloPlanificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(max_length=10)),
                ('hora_salida_prog', models.TimeField()),
                ('hora_llegada_prog', models.TimeField()),
                ('dias_semana', models.CharField(help_text='Ej: 1,3,5 (Lunes, Miércoles, Viernes)', max_length=15)),
                ('inicio_temporada', models.DateField()),
                ('fin_temporada', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('aerolinea_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad_iam.aerolineaempresa')),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion_global.diccaeronave')),
                ('aeropuerto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_destino_planificados', to='configuracion_global.diccaeropuerto')),
                ('aeropuerto_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_origen_planificados', to='configuracion_global.diccaeropuerto')),
            ],
            options={
                'verbose_name': 'Vuelo Planificado',
                'db_table': 'vuelos_planificados',
            },
        ),
        migrations.AddField(
            model_name='vuelodiario',
            name='vuelo_planificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuelos_aodb.vueloplanificado'),
        ),
    ]
