# Generated by Django 5.2.12 on 2026-05-07 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AerolineaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc_nit', models.CharField(max_length=30, unique=True)),
                ('tipo_empresa', models.CharField(max_length=30)),
                ('correo_contacto', models.EmailField(max_length=100)),
                ('celular_contacto', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aerolineas_empresas',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs_auditoria',
            },
        ),
        migrations.CreateModel(
            name='SesionCredencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(max_length=255, unique=True)),
                ('dispositivo', models.CharField(max_length=255)),
                ('ip_origen', models.GenericIPAddressField()),
                ('mfa_verificado', models.BooleanField(default=False)),
                ('estado', models.CharField(default='ACTIVA', max_length=20)),
                ('ultimo_acceso', models.DateTimeField(auto_now=True)),
                ('expira_at', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesiones_credenciales',
            },
        ),
        migrations.CreateModel(
            name='TorreControlPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia_atc', models.CharField(max_length=30, unique=True)),
                ('cargo_atc', models.CharField(max_length=50)),
                ('funcion_operativa', models.CharField(max_length=255)),
                ('vencimiento_licencia', models.DateField()),
                ('certificado_medico_vigente', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_atc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'torre_control_personal',
            },
        ),
    ]
